import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { api, HydrateClient } from "~/trpc/server";
import { SessionProvider } from "next-auth/react";
import ChatSidebar from "~/components/chat-sidebar";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const chats = await api.chat.list();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <HydrateClient>
            <SessionProvider>
              <div className="flex flex-row gap-5 h-screen max-w-[80%] mx-auto p-4 bg-gradient-to-b from-green-200 to-green-50 rounded-3xl shadow-lg">
                <div className="w-1/4">
                  <ChatSidebar chats={chats} />
                </div>
                <div className="w-3/4">
                  {children}
                </div>
              </div>
            </SessionProvider>
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
