import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { api, HydrateClient } from "~/trpc/server";
import ChatSidebar from "~/components/chat-sidebar";
import { auth } from "~/lib/auth"
import { headers } from "next/headers"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth.api.getSession({
    headers: await headers()
  })
  const chats = (session?.user.id) ? await api.chat.list() : [];

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <HydrateClient>
            <div className="flex flex-row gap-5 h-screen max-w-[80%] mx-auto p-4 bg-gradient-to-b from-green-200 to-green-50 rounded-3xl shadow-lg">
              <div className="w-1/4">
                <ChatSidebar chats={chats} />
              </div>
              <div className="w-3/4">
                {children}
              </div>
            </div>
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
